language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
      env: NOXDEBUG=yes

sudo: false

before_install:
  - if [ ! "$NOXDEBUG" = "yes" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install:
  - composer install
  - if [ "$CHECKS" = "yes" ]; then composer require satooshi/php-coveralls --dev; fi;
  - if [ "$CHECKS" = "yes" ]; then composer require squizlabs/php_codesniffer="~2.3" --dev; fi;

script:
  - if [ ! "$CHECKS" = "yes" ]; then phpunit; fi;
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=vendor .; fi;
  - >
    if [ "$CHECKS" = "yes" ]; then
      echo "zend_extension=xdebug.so" > build/xdebug.ini &&
      mkdir -p build/logs; &&
      phpenv config-add build/xdebug.ini &&
      phpunit --coverage-clover build/logs/clover.xml;
    fi;
  - if [ "$CHECKS" = "yes" ]; then ; fi;

after_success:
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/coveralls -c .coveralls.yml; fi;

notifications:
  email:
    on_success: change
    on_failure: always
