language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
      env: NOXDEBUG=yes

sudo: false

before_install:
  - source travis/before_install.sh

install:
  - if [ "$CHECKS" = "yes" ]; then source travis/install_normal.sh; else travis/install_checks.sh; fi;

script:
  - if [ "$CHECKS" = "yes" ]; then source travis/script_normal.sh; else travis/script_checks.sh; fi;

after_success:
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/coveralls -c travis/.coveralls.yml; fi;

notifications:
  email:
    on_success: change
    on_failure: always
