language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - if [ "$CHECKS" = "yes" ]; then mkdir -p build/logs; fi;
  - if [ "$CHECKS" = "yes" ]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi;
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=vendor .; fi;

after_script:
  - if [ "$CHECKS" = "yes" ]; then php coveralls -c .coveralls.yml; fi;
